version: '0.1'
services:
  mall-web:
    container_name: "mall-web"
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm run dev"]
    volumes:
      - ".:/app/"
      - "/app/node_modules"
    ports:
      - "3000:3000"
      - "8080:8080"
      - "8090:8090"
